### ISSUE TITLE
ActiveGate crashes on IPv6 only mode

### ISSUE THREAD

**Issue by olljanat** [Dynatrace/dynatrace-operator#392]
FYI. I noticed that ActiveGate is not able to run on dual-stack cluster where dynatrace namespace is set to use IPv6 only using Kyverno policy like this (like described on official dual-stack documentation https://kubernetes.io/docs/concepts/services-networking/dual-stack/ )
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ipv6-only
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: ipv6-only
    match:
      resources:
        kinds:
        - Service
        namespaces:
        - "dynatrace"
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
    mutate:
      patchStrategicMerge:
        spec:
          ipFamilyPolicy: SingleStack
          ipFamilies:
          - IPv6
```

Pod ends up to boot loop with error like this because DNS entrypoint is parsed incorrectly (should be `https://[fd::7a15]:443/communication` )
```
2021-11-29 09:26:52 UTC INFO    [<collector>] [<collector.core>, CollectorImpl] Initiating Collector Startup...
2021-11-29 09:26:52 UTC INFO    [<collector>] [<collector.core>, CollectorImpl] No keyfile detected, starting without crypto subsystem.
2021-11-29 09:26:52 UTC INFO    [<mvl43013>] [<collector.core>, CollectorImpl] Working mode property set to PRIVATE
2021-11-29 09:26:52 UTC INFO    [<mvl43013>] [<collector.core>, CollectorImpl] ActiveGate not configured, will configure now.
2021-11-29 09:26:52 UTC INFO    [<mvl43013>] [<collector.core>, CollectorImpl] Gateway token is configured
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.compuware.apm.util.shared.api.connectivity.UriBuilder (file:/opt/dynatrace/gateway/lib/util.shared-1.229.163.20211109-103203.jar) to field java.net.URI.schemeSpecificPart
WARNING: Please consider reporting this to the maintainers of com.compuware.apm.util.shared.api.connectivity.UriBuilder
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-11-29 09:26:53 UTC SEVERE  [<mvl43013>] [<collector.core>, CollectorImpl] Connectivity detection failed. Collector startup cancelled
com.compuware.apm.platform.shared.api.connectivity.ConnectivityDetectorException: DNS Entrypoint URI: https://fd::7a15:443/communication is invalid.
        at com.compuware.apm.platform.shared.connectivity.ConnectivityDetectorImpl.retrieveAndValidateDnsEntryPointUris(ConnectivityDetectorImpl.java:461)
        at com.compuware.apm.platform.shared.connectivity.ConnectivityDetectorImpl.newInstance(ConnectivityDetectorImpl.java:86)
        at com.compuware.apm.platform.shared.api.connectivity.ConnectivityDetectorFactory.createCollectorConnectivityDetector(ConnectivityDetectorFactory.java:27)
        at com.compuware.apm.collector.core.CollectorImpl.populateCollectorUris(CollectorImpl.java:1216)
        at com.compuware.apm.collector.core.CollectorImpl.activate(CollectorImpl.java:988)
        at com.compuware.apm.collector.core.CollectorImpl.main(CollectorImpl.java:767)
Caused by: java.lang.IllegalArgumentException: URI string: https:/communication - Host component for given scheme https is missing.
        at com.compuware.apm.util.shared.api.connectivity.UriBuilder.validateComponentsOfURI(UriBuilder.java:292)
        at com.compuware.apm.util.shared.api.connectivity.UriBuilder.build(UriBuilder.java:283)
        at com.compuware.apm.platform.shared.connectivity.ConnectivityDetectorImpl.retrieveAndValidateDnsEntryPointUris(ConnectivityDetectorImpl.java:432)
        ... 5 more
```

**Comment by chrismuellner** [comment]
Thanks for reporting this issue.
I'll close this here as it's not connected to the dynatrace-operator and have forwarded it to the ActiveGate team internally.

**Comment by mbrunn** [comment]
@chrismuellner could you please follow this up internally? This issue is still not fixed.

I am not entirely sure if it is only connected to the ActiveGate since the format for the IPv6-address is provided in the StatefulSet of the ActiveGate as it is defined by the operator? Or did you mean that the env var should already include the square brackets?

```
        containers:
        - env:
          - name: DT_DNS_ENTRY_POINT
            value: https://$(DYNAKUBE_ACTIVEGATE_SERVICE_HOST):$(DYNAKUBE_ACTIVEGATE_SERVICE_PORT)/communication,https://dynakube-activegate.dynatrace:$(DYNAKUBE_ACTIVEGATE_SERVICE_PORT)/communication
```

Regardless of which team is responsible, this issue is still not fixed and prevents Dynatrace to be used in an IPv6 only Kubernetes-Environment.
