### ISSUE TITLE
OCP 4.8 + DT Operator 0.7.0 -  invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by blccdy** [Dynatrace/dynatrace-operator#903]
We successfully installed the 0.7.0 operator using the non-csi [openshift.yaml](https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.7.0/openshift.yaml) in our Openshift 4.8 environment.

With the first creation of the dynakube CR, OneAgent and ActiveGate pods were created and we could successfully connect everything to our on premise Dynatrace server. 

Afterwards the dynatrace operator keeps crashing with an ` invalid memory address or nil pointer dereference` exception.

We uninstalled the operator and also deleted the namespace and deleted the CRD.
Installing the operator again still works, but now it crashes all the time. No OneAgent and ActiveGate pods are created.

I added the log of the operator, see below. Because we have a corperate ca, we use the `trustedCAs` field in our dynakube instance ([classicFullStack.yaml](https://github.com/Dynatrace/dynatrace-operator/blob/master/assets/samples/classicFullStack.yaml)), see also below. The stacktrace at `/app/src/dockerconfig/docker_config.go:84` shows that the certificate ca for accessing our on premise Dynatrace server is stored into a file. This seams to cause a null pointer exception. Because it worked once, all our configuration should be correct. 

```
{"level":"info","ts":"2022-06-29T07:08:28.381Z","logger":"dynatrace-operator-version","msg":"dynatrace-operator","version":"v0.7.0","gitCommit":"1790388d4085ac4f3cc58c489dbe1d05480b9e9c","buildDate":"2022-06-23T11:09:37+00:00","goVersion":"go1.18.3","platform":"linux/amd64"}
{"level":"info","ts":"2022-06-29T07:08:28.381Z","logger":"main","msg":"starting certificate bootstrapper","namespace":"dynatrace"}
I0629 07:08:29.529079       1 request.go:665] Waited for 1.046899176s due to client-side throttling, not priority and fairness, request: GET:https://10.219.0.1:443/apis/storage.k8s.io/v1beta1?timeout=32s
{"level":"info","ts":"2022-06-29T07:08:33.386Z","logger":"main.controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2022-06-29T07:08:33.387Z","logger":"main","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":"2022-06-29T07:08:33.387Z","logger":"main.controller.deployment","msg":"Starting EventSource","reconciler group":"apps","reconciler kind":"Deployment","source":"kind source: *v1.Deployment"}
{"level":"info","ts":"2022-06-29T07:08:33.387Z","logger":"main.controller.deployment","msg":"Starting Controller","reconciler group":"apps","reconciler kind":"Deployment"}
{"level":"info","ts":"2022-06-29T07:08:33.488Z","logger":"main.controller.deployment","msg":"Starting workers","reconciler group":"apps","reconciler kind":"Deployment","worker count":1}
{"level":"info","ts":"2022-06-29T07:08:33.488Z","logger":"webhook-certificates","msg":"reconciling webhook certificates","namespace":"dynatrace","name":"dynatrace-webhook"}
{"level":"info","ts":"2022-06-29T07:08:33.498Z","logger":"webhook-certificates","msg":"secret for certificates up to date, skipping update"}
{"level":"info","ts":"2022-06-29T07:08:33.498Z","logger":"webhook-certificates","msg":"stopping manager after certificates creation"}
{"level":"info","ts":"2022-06-29T07:08:33.499Z","logger":"main","msg":"Stopping and waiting for non leader election runnables"}
{"level":"info","ts":"2022-06-29T07:08:33.499Z","logger":"main","msg":"Stopping and waiting for leader election runnables"}
{"level":"info","ts":"2022-06-29T07:08:33.499Z","logger":"main.controller.deployment","msg":"Shutdown signal received, waiting for all workers to finish","reconciler group":"apps","reconciler kind":"Deployment"}
{"level":"info","ts":"2022-06-29T07:08:33.499Z","logger":"main.controller.deployment","msg":"All workers finished","reconciler group":"apps","reconciler kind":"Deployment"}
{"level":"info","ts":"2022-06-29T07:08:33.499Z","logger":"main","msg":"Stopping and waiting for caches"}
{"level":"info","ts":"2022-06-29T07:08:33.499Z","logger":"main","msg":"Stopping and waiting for webhooks"}
{"level":"info","ts":"2022-06-29T07:08:33.499Z","logger":"main","msg":"Wait completed, proceeding to shutdown the manager"}
{"level":"info","ts":"2022-06-29T07:08:33.499Z","logger":"main","msg":"starting operator","namespace":"dynatrace"}
{"level":"info","ts":"2022-06-29T07:08:38.455Z","logger":"main.controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2022-06-29T07:08:38.455Z","logger":"main","msg":"registering manager components"}
{"level":"info","ts":"2022-06-29T07:08:38.455Z","logger":"main","msg":"starting manager"}
{"level":"info","ts":"2022-06-29T07:08:38.455Z","logger":"main","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":"2022-06-29T07:08:38.455Z","logger":"main","msg":"Starting server","kind":"health probe","addr":"[::]:10080"}
I0629 07:08:38.455964       1 leaderelection.go:248] attempting to acquire leader lease dynatrace/dynatrace-operator-lock...
I0629 07:08:54.544354       1 leaderelection.go:258] successfully acquired lease dynatrace/dynatrace-operator-lock
{"level":"info","ts":"2022-06-29T07:08:54.544Z","logger":"main.events","msg":"Normal","object":{"kind":"ConfigMap","namespace":"dynatrace","name":"dynatrace-operator-lock","uid":"4d1edc81-a7f4-4d1a-8713-15e7ce53fc97","apiVersion":"v1","resourceVersion":"432110370"},"reason":"LeaderElection","message":"dynatrace-operator-7bfc999888-zv5sm_5d8b551d-cbbd-4cb0-a5b4-6627c95b0bb6 became leader"}
{"level":"info","ts":"2022-06-29T07:08:54.544Z","logger":"main.controller.dynakube","msg":"Starting EventSource","reconciler group":"dynatrace.com","reconciler kind":"DynaKube","source":"kind source: *v1beta1.DynaKube"}
{"level":"info","ts":"2022-06-29T07:08:54.544Z","logger":"main.controller.dynakube","msg":"Starting EventSource","reconciler group":"dynatrace.com","reconciler kind":"DynaKube","source":"kind source: *v1.StatefulSet"}
{"level":"info","ts":"2022-06-29T07:08:54.544Z","logger":"main.controller.dynakube","msg":"Starting EventSource","reconciler group":"dynatrace.com","reconciler kind":"DynaKube","source":"kind source: *v1.DaemonSet"}
{"level":"info","ts":"2022-06-29T07:08:54.544Z","logger":"main.controller.deployment","msg":"Starting EventSource","reconciler group":"apps","reconciler kind":"Deployment","source":"kind source: *v1.Deployment"}
{"level":"info","ts":"2022-06-29T07:08:54.544Z","logger":"main.controller.dynakube","msg":"Starting Controller","reconciler group":"dynatrace.com","reconciler kind":"DynaKube"}
{"level":"info","ts":"2022-06-29T07:08:54.544Z","logger":"main.controller.deployment","msg":"Starting Controller","reconciler group":"apps","reconciler kind":"Deployment"}
{"level":"info","ts":"2022-06-29T07:08:54.544Z","logger":"main.controller.node","msg":"Starting EventSource","reconciler group":"","reconciler kind":"Node","source":"kind source: *v1.Node"}
{"level":"info","ts":"2022-06-29T07:08:54.544Z","logger":"main.controller.node","msg":"Starting Controller","reconciler group":"","reconciler kind":"Node"}
{"level":"info","ts":"2022-06-29T07:08:54.645Z","logger":"main.controller.deployment","msg":"Starting workers","reconciler group":"apps","reconciler kind":"Deployment","worker count":1}
{"level":"info","ts":"2022-06-29T07:08:54.645Z","logger":"webhook-certificates","msg":"reconciling webhook certificates","namespace":"dynatrace","name":"dynatrace-webhook"}
{"level":"info","ts":"2022-06-29T07:08:54.645Z","logger":"main.controller.node","msg":"Starting workers","reconciler group":"","reconciler kind":"Node","worker count":1}
{"level":"info","ts":"2022-06-29T07:08:54.646Z","logger":"main.controller.dynakube","msg":"Starting workers","reconciler group":"dynatrace.com","reconciler kind":"DynaKube","worker count":1}
{"level":"info","ts":"2022-06-29T07:08:54.646Z","logger":"dynakube-controller","msg":"reconciling DynaKube","namespace":"dynatrace","name":"dynakube-ea"}
{"level":"info","ts":"2022-06-29T07:08:54.660Z","logger":"webhook-certificates","msg":"secret for certificates up to date, skipping update"}
{"level":"info","ts":"2022-06-29T07:08:54.903Z","logger":"dynakube-status","msg":"updating DynaKube CR","cause":"token conditions updated","dynakube":"dynakube-ea"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x142695c]

goroutine 1058 [running]:
github.com/spf13/afero.WriteFile({0x0?, 0x0?}, {0xc00355dec0?, 0x5?}, {0xc0001b3000, 0xba9, 0xc00}, 0x2214a88?)
	/go/pkg/mod/github.com/spf13/afero@v1.8.0/ioutil.go:126 +0x3c
github.com/spf13/afero.Afero.WriteFile(...)
	/go/pkg/mod/github.com/spf13/afero@v1.8.0/ioutil.go:122
github.com/Dynatrace/dynatrace-operator/src/dockerconfig.(*DockerConfig).SaveCustomCAs(0xc002f33c40, {0x22034d0, 0xc003610c30}, {{0x0?, 0x0?}}, {0xc00355dec0, 0x2d})
	/app/src/dockerconfig/docker_config.go:84 +0x166
github.com/Dynatrace/dynatrace-operator/src/controllers/dynakube/version.ReconcileVersions({0x22034d0, 0xc003610c30}, 0xc002815bb8, {0x7fe5010d4300, 0xc000260230}, {{0x0?, 0x0?}}, 0x21e05f0?)
	/app/src/controllers/dynakube/version/version.go:67 +0x76b
github.com/Dynatrace/dynatrace-operator/src/controllers/dynakube.(*DynakubeController).reconcileDynaKube(0xc000260380, {0x22034d0, 0xc003610c30}, 0xc002815bb8, 0xc002815c40)
	/app/src/controllers/dynakube/dynakube_controller.go:220 +0x785
github.com/Dynatrace/dynatrace-operator/src/controllers/dynakube.(*DynakubeController).Reconcile(0xc000260380, {0x22034d0, 0xc003610c30}, {{{0xc002f05b80?, 0x1df6be0?}, {0xc002f05be0?, 0x30?}}})
	/app/src/controllers/dynakube/dynakube_controller.go:123 +0x41d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc002a73290, {0x22034d0, 0xc003610b10}, {{{0xc002f05b80?, 0x1df6be0?}, {0xc002f05be0?, 0x411054?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x27e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc002a73290, {0x2203428, 0xc00338cf00}, {0x1cde680?, 0xc003526500?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x349
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc002a73290, {0x2203428, 0xc00338cf00})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x31c

```

```
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  creationTimestamp: '2022-06-29T08:30:06Z'
  generation: 1
  managedFields: [...]
  name: dynakubeea
  namespace: dynatrace
  resourceVersion: '432253344'
  uid: 3c827ae9-98ac-4189-a620-4982ac99007c
spec:
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    resources:
      limits:
        cpu: 2500m
        memory: 1.5Gi
      requests:
        cpu: 1500m
        memory: 1Gi
  apiUrl: 'https://***/e/***/api'
  oneAgent:
    classicFullStack:
      args:
        - '--set-host-group=dev'
      oneAgentResources:
        limits:
          cpu: 500m
          memory: 1.5Gi
        requests:
          cpu: 300m
          memory: 512Mi
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
  trustedCAs: dynakubeca
```

**Comment by speer** [comment]
We are having the exact same issue on Kubernetes 1.22 and 0.7.0, also with custom trustedCAs configured.

**Comment by Forcebyte** [comment]
Thank you @luhi-DT!

Is there any chance a new version of the DT operator can be released with the fixes within #909?

We're currently getting the following, which I presume to be fixed under the docker config changes that were made
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x142695c]

goroutine 1058 [running]:
github.com/spf13/afero.WriteFile({0x0?, 0x0?}, {0xc00355dec0?, 0x5?}, {0xc0001b3000, 0xba9, 0xc00}, 0x2214a88?)
	/go/pkg/mod/github.com/spf13/afero@v1.8.0/ioutil.go:126 +0x3c
github.com/spf13/afero.Afero.WriteFile(...)
	/go/pkg/mod/github.com/spf13/afero@v1.8.0/ioutil.go:122
github.com/Dynatrace/dynatrace-operator/src/dockerconfig.(*DockerConfig).SaveCustomCAs(0xc002f33c40, {0x22034d0, 0xc003610c30}, {{0x0?, 0x0?}}, {0xc00355dec0, 0x2d})
	/app/src/dockerconfig/docker_config.go:84 +0x166
github.com/Dynatrace/dynatrace-operator/src/controllers/dynakube/version.ReconcileVersions({0x22034d0, 0xc003610c30}, 0xc002815bb8, {0x7fe5010d4300, 0xc000260230}, {{0x0?, 0x0?}}, 0x21e05f0?)
	/app/src/controllers/dynakube/version/version.go:67 +0x76b
github.com/Dynatrace/dynatrace-operator/src/controllers/dynakube.(*DynakubeController).reconcileDynaKube(0xc000260380, {0x22034d0, 0xc003610c30}, 0xc002815bb8, 0xc002815c40)
	/app/src/controllers/dynakube/dynakube_controller.go:220 +0x785
github.com/Dynatrace/dynatrace-operator/src/controllers/dynakube.(*DynakubeController).Reconcile(0xc000260380, {0x22034d0, 0xc003610c30}, {{{0xc002f05b80?, 0x1df6be0?}, {0xc002f05be0?, 0x30?}}})
	/app/src/controllers/dynakube/dynakube_controller.go:123 +0x41d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc002a73290, {0x22034d0, 0xc003610b10}, {{{0xc002f05b80?, 0x1df6be0?}, {0xc002f05be0?, 0x411054?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114 +0x27e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc002a73290, {0x2203428, 0xc00338cf00}, {0x1cde680?, 0xc003526500?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311 +0x349
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc002a73290, {0x2203428, 0xc00338cf00})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:223 +0x31c
```

for now we're working around this by hardcoding `SkipCertCheck` to True, so its not currently causing a breaking issue

**Comment by luhi-DT** [comment]
Hi @Forcebyte, 
we are planning to do v0.7.1 in the next days (no exact date yet when available). This will include a fix for the above mentioned issue :) Thanks!

**Comment by Forcebyte** [comment]
Sounds good, thank you Luhi!~
